### ISSUE TITLE
Move to namespace usage instead of current schema to name files

### ISSUE THREAD

**Issue by simondevenish** [libtcod/treeburner#2]
Original files are named such as namespace_filename.hpp where this could be simplifed to just filename.hpp and move objects into respective namespaces such as map::building etc. I can move the code over to this new structure

**Comment by simondevenish** [comment]
I've started work on this. It does add some extra syntax, but provides a lot more context and readability of what objects relate to where they are being pulled from. As an example the array:
`terrainTypes[terrainId]` is being used across a fair few files and at first glance it is not obvious whether this is a local variable to the class using it or whether it is coming from another object. By using namespace scoping it becomes obvious:
`map::cell::terrainTypes[terrainId]`

**Comment by simondevenish** [comment]
I also reccomend that all files relating to a namespace should be moved into a sub directory. The directory structure would then become something like src/map for the map namespace, instead of everything living under src. What do you think @HexDecimal

**Comment by HexDecimal** [comment]
I'm always okay with switching over to namespaces.  When it makes sense I'm also okay with using sub-directories.  The current file names suggest that directories are a good idea.

I'm also okay with breaking changes to Umbra if that happens.  Since that needs to be updated to use namespaces as well.

**Comment by simondevenish** [comment]
@HexDecimal This is now completed
